import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useState } from "react"
import Header from './Header'
import Code from './code.json';
import styles from '../styles/Home.module.css'

const proptitle = 'TK PORTFOLIO';


export default function Webdesign() {
  // console.log(Code.wd);
    
    let Arr1 = [];
    let Arr2 = [];
    let ArrImage = [];
    let ArrImage2 = [];
    const WdData = Code.wd;
    const WDD = WdData.map((item) =>
      Arr2 = [...Arr1 ,<div id={item.id}><p>{item.display}<span>{item.year}</span></p><p>{item.descript}</p></div> ,<figure><img src={item.image} alt="" /></figure>]
      )
      console.log(WDD);
     

  return (
    <div className={styles.container}>
      <Head>
        <title>{proptitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <div className={styles.WDimgwrap}>
      <h1 className={styles.FVTitle}>TOSHIYUKI<span></span>KIMURA<span></span>PORTFOLIO</h1>
        <p className={styles.abtitle}>WEB DESIGN UI/UX DESIGN</p>
      </div>

      <main className={styles.main}>
        <div className={styles.WdData}>
        {WDD}
        </div>
      </main>

      <footer id='footer' className={styles.footer}>
      
      </footer>
    </div>
  )
}
